project:
  type: book

book:
  title: A Hotchpotch for the Biometrician
  date: today
  chapters:
    - index.qmd
    - asreml-depends.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    published-title: "Last modified on"