project:
  type: website

website:
  title: A Hotchpotch for the Biometrician
  navbar:
    left:
      - href: index.qmd
        text: Home
  search: 
      location: navbar
      type: textbox

format:
  html:
    theme: united
    published-title: "Last modified on"